"use client";
import { useState, useMemo } from "react";
import {
  IncidentWithDetails,
  IncidentStatus,
  Priority,
  UserRole,
  Urgency,
  Impact,
} from "@/types/globals";
import { CardTitle, CardDescription } from "@/components/ui/card";
import { TicketConsoleFilters } from "@/app/incidents/components/TicketConsoleFilters";
import DataTable from "./components/data-table";   

const mockUser = {
  id: "1",
  name: "John Doe",
  email: "john.doe@example.com",
  role: UserRole.SERVICE_DESK,
  createdAt: new Date(),
  updatedAt: new Date(),
};

function getData(): IncidentWithDetails[] {
  // Fetch data from your API here.
  return [
    {
      id: "1",
      number: "INC-001",
      title: "Email server not responding",
      description: "Users cannot send or receive emails",
      status: IncidentStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      impact: Impact.HIGH,
      urgency: Urgency.HIGH,
      category: "Email",
      subcategory: "Outage",
      reportedBy: { ...mockUser, id: "2", name: "Jane Smith" },
      assignedTo: null,
      assignmentGroup: "Email Support",
      slaBreachTime: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24h from now
      businessService: "Email Service",
      location: "Headquarters",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "2",
      number: "INC-002",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.NEW,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "3",
      number: "INC-003",
      title: "VPN connection issues",
      description:
        "Unable to connect to the corporate VPN from remote locations",
      status: IncidentStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      impact: Impact.HIGH,
      urgency: Urgency.HIGH,
      category: "Network",
      subcategory: "VPN",
      reportedBy: { ...mockUser, id: "4", name: "Sarah Williams" },
      assignedTo: null,
      assignmentGroup: "",
      slaBreachTime: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2h ago (overdue)
      businessService: "Remote Access",
      location: "All Locations",
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "4",
      number: "INC-004",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.RESOLVED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "5",
      number: "INC-005",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.ON_HOLD,
      priority: Priority.CRITICAL,
      impact: Impact.CRITICAL,
      urgency: Urgency.CRITICAL,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "6",
      number: "INC-006",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CANCELLED,
      priority: Priority.LOW,
      impact: Impact.LOW,
      urgency: Urgency.LOW,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "7",
      number: "INC-007",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "8",
      number: "INC-008",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "9",
      number: "INC-009",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "10",
      number: "INC-010",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "11",
      number: "INC-011",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "12",
      number: "INC-012",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "13",
      number: "INC-013",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "14",
      number: "INC-014",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "15",
      number: "INC-015",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "16",
      number: "INC-016",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "17",
      number: "INC-017",
      title: "Email server not responding",
      description: "Users cannot send or receive emails",
      status: IncidentStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      impact: Impact.HIGH,
      urgency: Urgency.HIGH,
      category: "Email",
      subcategory: "Outage",
      reportedBy: { ...mockUser, id: "2", name: "Jane Smith" },
      assignedTo: null,
      assignmentGroup: "Email Support",
      slaBreachTime: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24h from now
      businessService: "Email Service",
      location: "Headquarters",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "18",
      number: "INC-018",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.NEW,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "19",
      number: "INC-019",
      title: "VPN connection issues",
      description:
        "Unable to connect to the corporate VPN from remote locations",
      status: IncidentStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      impact: Impact.HIGH,
      urgency: Urgency.HIGH,
      category: "Network",
      subcategory: "VPN",
      reportedBy: { ...mockUser, id: "4", name: "Sarah Williams" },
      assignedTo: null,
      assignmentGroup: "",
      slaBreachTime: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2h ago (overdue)
      businessService: "Remote Access",
      location: "All Locations",
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "20",
      number: "INC-020",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.RESOLVED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "21",
      number: "INC-021",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.ON_HOLD,
      priority: Priority.CRITICAL,
      impact: Impact.CRITICAL,
      urgency: Urgency.CRITICAL,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "22",
      number: "INC-022",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CANCELLED,
      priority: Priority.LOW,
      impact: Impact.LOW,
      urgency: Urgency.LOW,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "23",
      number: "INC-023",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "24",
      number: "INC-024",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: " 25",
      number: "INC-025",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "26",
      number: "INC-026",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "27",
      number: "INC-027",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "28",
      number: "INC-028",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "29",
      number: "INC-029",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "30",
      number: "INC-030",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "31",
      number: "INC-031",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "32",
      number: "INC-032",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "33",
      number: "INC-033",
      title: "Email server not responding",
      description: "Users cannot send or receive emails",
      status: IncidentStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      impact: Impact.HIGH,
      urgency: Urgency.HIGH,
      category: "Email",
      subcategory: "Outage",
      reportedBy: { ...mockUser, id: "2", name: "Jane Smith" },
      assignedTo: null,
      assignmentGroup: "Email Support",
      slaBreachTime: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24h from now
      businessService: "Email Service",
      location: "Headquarters",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "34",
      number: "INC-034",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.NEW,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "35",
      number: "INC-035",
      title: "VPN connection issues",
      description:
        "Unable to connect to the corporate VPN from remote locations",
      status: IncidentStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      impact: Impact.HIGH,
      urgency: Urgency.HIGH,
      category: "Network",
      subcategory: "VPN",
      reportedBy: { ...mockUser, id: "4", name: "Sarah Williams" },
      assignedTo: null,
      assignmentGroup: "",
      slaBreachTime: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2h ago (overdue)
      businessService: "Remote Access",
      location: "All Locations",
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "36",
      number: "INC-036",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.RESOLVED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "37",
      number: "INC-037",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.ON_HOLD,
      priority: Priority.CRITICAL,
      impact: Impact.CRITICAL,
      urgency: Urgency.CRITICAL,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "38",
      number: "INC-038",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CANCELLED,
      priority: Priority.LOW,
      impact: Impact.LOW,
      urgency: Urgency.LOW,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "39",
      number: "INC-039",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "40",
      number: "INC-040",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "41",
      number: "INC-041",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "42",
      number: "INC-042",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "43",
      number: "INC-043",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "44",
      number: "INC-044",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "45",
      number: "INC-045",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "46",
      number: "INC-046",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "47",
      number: "INC-047",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "48",
      number: "INC-048",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "49",
      number: "INC-049",
      title: "Email server not responding",
      description: "Users cannot send or receive emails",
      status: IncidentStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      impact: Impact.HIGH,
      urgency: Urgency.HIGH,
      category: "Email",
      subcategory: "Outage",
      reportedBy: { ...mockUser, id: "2", name: "Jane Smith" },
      assignedTo: null,
      assignmentGroup: "Email Support",
      slaBreachTime: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24h from now
      businessService: "Email Service",
      location: "Headquarters",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "50",
      number: "INC-050",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.NEW,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "51",
      number: "INC-051",
      title: "VPN connection issues",
      description:
        "Unable to connect to the corporate VPN from remote locations",
      status: IncidentStatus.IN_PROGRESS,
      priority: Priority.HIGH,
      impact: Impact.HIGH,
      urgency: Urgency.HIGH,
      category: "Network",
      subcategory: "VPN",
      reportedBy: { ...mockUser, id: "4", name: "Sarah Williams" },
      assignedTo: null,
      assignmentGroup: "",
      slaBreachTime: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2h ago (overdue)
      businessService: "Remote Access",
      location: "All Locations",
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "52",
      number: "INC-052",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.RESOLVED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "53",
      number: "INC-053",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.ON_HOLD,
      priority: Priority.CRITICAL,
      impact: Impact.CRITICAL,
      urgency: Urgency.CRITICAL,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "54",
      number: "INC-054",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CANCELLED,
      priority: Priority.LOW,
      impact: Impact.LOW,
      urgency: Urgency.LOW,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "55",
      number: "INC-055",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "56",
      number: "INC-056",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "58",
      number: "INC-058",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "59",
      number: "INC-059",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: null,
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "60",
      number: "INC-060",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "61",
      number: "INC-061",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "62",
      number: "INC-062",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "63",
      number: "INC-063",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "64",
      number: "INC-064",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
    {
      id: "65",
      number: "INC-065",
      title: "Printer not working in Marketing",
      description: "The color printer in the marketing department is jammed",
      status: IncidentStatus.CLOSED,
      priority: Priority.MEDIUM,
      impact: Impact.MEDIUM,
      urgency: Urgency.MEDIUM,
      category: "Hardware",
      subcategory: "Printer",
      reportedBy: { ...mockUser, id: "3", name: "Mike Johnson" },
      assignedTo: { ...mockUser, id: "1", name: "John Doe" },
      assignmentGroup: "Printer Support",
      slaBreachTime: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12h from now
      businessService: "Printing Services",
      location: "Marketing Department",
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
      updatedAt: new Date(),
      comments: [],
      history: [],
      _count: { comments: 0 },
    },
  ];
}

const IncidentConsolePage = () => {
  const data = getData();
  const [filters, setFilters] = useState<{
    search: string;
    statuses: IncidentStatus[];
    priorities: Priority[];
    assignedToMe: boolean;
    overdueOnly: boolean;
    dateRange: { from: Date | null; to: Date | null };
  }>({
    search: "",
    statuses: [],
    priorities: [],
    assignedToMe: false,
    overdueOnly: false,
    dateRange: { from: null, to: null },
  });

  const filteredIncidents = useMemo(() => {
    return data.filter((incident) => {
      // Search filter
      const matchesSearch =
        incident.title.toLowerCase().includes(filters.search.toLowerCase()) ||
        incident.number.toLowerCase().includes(filters.search.toLowerCase()) ||
        incident.description
          .toLowerCase()
          .includes(filters.search.toLowerCase());

      // Status filter
      const matchesStatus =
        filters.statuses.length === 0 ||
        filters.statuses.includes(incident.status);

      // Priority filter
      const matchesPriority =
        filters.priorities.length === 0 ||
        filters.priorities.includes(incident.priority);

      // Assigned to me filter
      const matchesAssignedToMe =
        !filters.assignedToMe || incident.assignedTo?.id === "1"; // Assuming current user ID is '1'

      // Overdue filter
      const isOverdue =
        incident.slaBreachTime && incident.slaBreachTime < new Date();
      const matchesOverdue = !filters.overdueOnly || isOverdue;

      return (
        matchesSearch &&
        matchesStatus &&
        matchesPriority &&
        matchesAssignedToMe &&
        matchesOverdue
      );
    });
  }, [filters]);

  const resetFilters = () => {
    setFilters({
      search: "",
      statuses: [],
      priorities: [],
      assignedToMe: true,
      overdueOnly: false,
      dateRange: { from: null, to: null },
    });
  };

  return (
    <div className="flex flex-1 flex-col h-full">
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>Ticket Console</CardTitle>
            <CardDescription>
              Filter and manage your assigned tickets
            </CardDescription>
          </div>
        </div>
        <TicketConsoleFilters
          filters={filters}
          onFiltersChange={setFilters}
          onReset={resetFilters}
        />

        <DataTable data={filteredIncidents} />
      </div>
    </div>
  );
};

export default IncidentConsolePage;
